# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build-application
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
          
- stage: Deploy
  jobs:
  - job: Deploy-app
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'azure connection'
        appType: 'webApp'
        WebAppName: 'wordreplace1'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
