# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - refs/heads/main
  batch: True

variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildConfiguration
  value: Release

stages:
- stage: Build
  jobs:
  - job: Build_application
    pool:
      vmImage: windows-latest
    steps:
      - task: VSBuild@1
        displayName: Build solution
        inputs:
          solution: $(BuildParameters.solution)
          msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
      #- task: DotNetCoreCLI@2
      #  inputs:
       #   command: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
          
- stage: Deploy
  jobs:
  - job: Deploy_app
    dependsOn: Build_application
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'azure connection'
        appType: 'webApp'
        WebAppName: 'wordreplace1'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
